### ISSUE TITLE
Error running on Windows

### ISSUE THREAD

**Issue by mikesigs** [pbar1/mfaws#1]
```
Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)
```

**Comment by pbar1** [comment]
It was an error in the deploy script - resubmitted to Chocolatey (version to be 1.0.3), so a `choco upgrade mfaws` should fix it.

**Comment by mikesigs** [comment]
Success! Thanks dude!
